=== 74R45/IntellectualNetworks2020_Labs/src/main/scala/x74r45/lab1/books-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
              <xs:element name="publisher" type="xs:string"/>
              <xs:element name="year" type="xs:short"/>
              <xs:element name="ISBN">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:pattern value="[0-9]{3}-[0-9]{3}-[0-9]{3}-[A-Z0-9]"/>
                </xs:restriction>
              </xs:simpleType>
              </xs:element>
              <xs:element name="price" type="xs:decimal" minOccurs="0"/>
              <xs:element name="numPages" type="xs:unsignedInt" minOccurs="0"/>
              <xs:element name="language" type="xs:string"/>
              <xs:element name="genre" type="xs:string"/>
              <xs:element name="rating" minOccurs="0">
              <xs:simpleType>
                <xs:restriction base="xs:decimal">
                  <xs:minInclusive value="0.0"/>
                  <xs:maxInclusive value="100.0"/>
                </xs:restriction>
              </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="rare" type="xs:boolean"/>
            <xs:attribute name="forSale" type="xs:boolean"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 74R45/IntellectualNetworks2020_Labs/src/main/scala/x74r45/lab1/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="books-schema.xsd">
  <book forSale="false" rare="false">
    <title>The Great Gatsby</title>
    <author>F. Scott Fitzgerald</author>
    <publisher>Chatto &amp; Windus</publisher>
    <year>1925</year>
    <ISBN>978-074-327-3</ISBN>
    <numPages>218</numPages>
    <language>English</language>
    <genre>Tragedy</genre>
    <rating>93.2</rating>
  </book>
  <book forSale="true" rare="false">
    <title>Odyssey</title>
    <author>Homer</author>
    <publisher>Macmillan</publisher>
    <year>1488</year>
    <ISBN>978-031-286-9</ISBN>
    <price>27.99</price>
    <numPages>432</numPages>
    <language>English</language>
    <genre>Epic poetry</genre>
    <rating>87.3</rating>
  </book>
  <book forSale="false" rare="true">
    <title>Mr. William Shakespeare's Comedies, Histories, &amp; Tragedies</title>
    <author>William Shakespeare</author>
    <publisher>Edward Blount</publisher>
    <year>1623</year>
    <ISBN>972-321-644-3</ISBN>
    <numPages>900</numPages>
    <language>English</language>
    <genre>English Renaissance theatre</genre>
    <rating>100.0</rating>
  </book>
</collection>
